package:
  name: gtk2-feature
  version: 1.0

build:
  number: 1
  track_features:
    - gtk2

about:
    home: http://www.gtk.org
    license: LGPL version 2.1
    summary: Multi-platform toolkit for creating graphical user interfaces. Metapackage for adding the gtk2 feature.
